# Generated by Django 5.2 on 2026-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
